### ISSUE TITLE
Missing Geojson library

### ISSUE THREAD

**Issue by Didymograptus** [open-geotechnical/ogt-ags-py#1]
I tried to convert an ags file to json, but got the following error:
Traceback (most recent call last):
  File "C:\Users\Tony-i5\Downloads\ogt-ags-py-master\ogt-ags-py-master\ogt-cli.p
y", line 8, in <module>
    import ogt.ogt_doc
  File "C:\Users\Tony-i5\Downloads\ogt-ags-py-master\ogt-ags-py-master\ogt\ogt_d
oc.py", line 9, in <module>
    import geojson
ImportError: No module named geojson

**Comment by pedromorgan** [comment]
Still TODO is the "setup.py" script + packaging.
requirements are listed in https://github.com/open-geotechnical/ogt-ags-py/blob/master/requirements.txt
(sphinx is only required to generate docs so need to remove)

```
pip install geojson
```

**Comment by Didymograptus** [comment]
My mistake - Perhaps we could list dependencies in the readme for now?

**Comment by Didymograptus** [comment]
Done
